### PR TITLE
Conf file reorg

### PR DESCRIPTION
**Pull request by nelson-lojo**
Prepping modularity for eventual scale-down experiments.

The changes attempt to make experiment configs be only "inherit"/"import" statements along with instance-specific tags.

As an illustrative example, here is the configuration file for training the "causal relu" (standard size) model on the sparse linear regression task:

```yaml
inherit:
    - ../models/standard_relu_causal.yaml
    - ../tasks/sparse_linear_regression.yaml
    - ../base_train.yaml
    - ../base_curriculum.yaml

training:
    resume_id: pretrained_relu_causal

wandb:
    name: "sparse_linear_standard_relu_causal"
```

### CODE REVIEW

**Review by DerrickhSun — APPROVED** [review]

**Comment by DerrickhSun** [comment]
I tried to run "python train.py --config conf/experiments/dt_relu.yaml", but it returned the error:
image

**Comment by DerrickhSun** [comment]
For comparison, experiments/linear.yaml ran just fine

**Comment by nelson-lojo** [comment]
Added file and updated `.gitignore`

**Review by DerrickhSun — APPROVED** [review]
Seems to all look fine, the .gitignore update fixed the problem

**Pull request merged**
